{{ if .Values.namespaces }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: blinkt-k8s-pod-placement
    {{- include "blinkt-k8s-pod-visualization.labels" . | nindent 4 }}  
data:
  namespaces.json: |-
{{ .Values.namespaces | indent 4 }}
{{ else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: blinkt-k8s-pod-placement
    {{- include "blinkt-k8s-pod-visualization.labels" . | nindent 4 }}  
data:
  namespaces.json: |-
    {
      "kube-system": { "r": 128, "g": 128, "b": 128}
    }
{{ end }}