name: blinkt-k8s-pod-visualization
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Docker login
        run: docker login --username ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }} --password ${{ secrets.DOCKER_HUB_REGISTRY_SECRET }}
      - name: Run Buildx
        run: docker buildx build --platform linux/arm/v6,linux/arm/v7,linux/arm/amd64 --file Dockerfile --tag chriskinsman/blinkt-k8s-pod-visualization:1.0.$GITHUB_RUN_NUMBER --tag chriskinsman/blinkt-k8s-pod-visualization:latest --output "type=image,push=true" .
